name: Update Dramas List

on:
  schedule:
    - cron: "0 12 * * 1"   # runs every Monday at 12:00 UTC
  workflow_dispatch:       # lets you run manually from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updated dramas.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dramas.json
          git commit -m "Auto-update dramas.json"
          git push
